sayMe :: Int -> String
sayMe 1 = "素数を数えるんだ"
sayMe 2 = ""
sayMe 3 = "3"
sayMe 4 = "素数を数えるんだ"
sayMe 5 = "5"
sayMe 6 = "素数を数えるんだ"
sayMe 7 = "7"
sayMe 8 = "素数を数えるんだ"
sayMe 9 = "素数を数えるんだ"
sayMe 10 = "素数を数えるんだ"
sayMe x = "I can't count"